%% ===readme===

% descrip: matlab scripts plot Nonlinear Ekman vertical heat flux Q
% based on Stern (1965) formulation  
% 2) Stern nonlinear Ekman vertical pumping velocity
% 1) linear Ekman vertical pumping velocity
% 3) CESM model output

% update history:
% v1.0 DL 2019Dec05
% v1.1 DL 2019Dec09
% v1.2 DL 2020Feb05

% extra notes:
% =============


%% === set up environments ===
clear all;close all;clc;

  date_str='2020Mar18'; 

% --- summer seasons ---
header = 'This file was generated by DL via code ComputeSaveQekmanEddyGlobalOctMarAv_2020Mar18.m';
infileAv = ['../data_after_manipulation/TauKesaiRoWvelTempGlobalOctMarAv_2020Mar17.mat'];
outfileQ = ['../data_after_manipulation/QekmanEddyGlobalOctMarAv_',date_str,'.mat'];
MonSea = [01 02 03 10 11 12]; % winter
% ----------------------

addpath(genpath('Func4EkmanProject/'))

% Constants4CESM_Global

wt_te_prim_csum = 0;
wt_ne_prim_csum = 0;
wt_le_prim_csum = 0;
wt_ce_prim_csum = 0;
Ndays = 0; % number of loops
rho_w = 1020;
Cp    = 3.99e3; % [J/kg/k] the specific heat at constant pressure (Thorpe 2007)
%=============================


%% === data loading and analysis ===
Av = load(infileAv);
w_te_av = Av.w_te_TimeAv;
w_ne_av = Av.w_ne_TimeAv;
w_le_av = Av.w_le_TimeAv;
w_ce_av = Av.w_ce_TimeAv;
Tw_av   = Av.Tw_TimeAv;
lon_1d  = Av.lon_1d;
lat_1d  = Av.lat_1d;
z_wvel_ce= Av.z_wvel_ce;
z_Tw    = Av.z_Tw;
clear Av

for iyr = 87:90
  for imon = MonSea
      
%% === load data ===
infile  = ['../data_after_manipulation/WvelTempGlobal_CESM_', ...
    num2str(iyr),'-',num2str(imon,'%02d'),'.mat'];
disp(['loading ', infile])
dummy = load(infile);
w_te_3d = dummy.w_te_3d;
w_ne_3d = dummy.w_ne_3d;
w_le_3d = dummy.w_le_3d;
w_ce_3d = dummy.w_ce_3d;
Tw_3d   = dummy.Tw_3d;
clear infile dummy
ntime = size(Tw_3d,3); % time dimension
% ==================


%% === data analysis ===
for iday = 1 : ntime % loop through time
disp(['analyzing day ', num2str(iday,'%02d')])

% --- compute w', T', w'T' --- 
w_te_prim = w_te_3d(:,:,iday)-w_te_av;
w_ne_prim = w_ne_3d(:,:,iday)-w_ne_av;
w_le_prim = w_le_3d(:,:,iday)-w_le_av;
w_ce_prim = w_ce_3d(:,:,iday)-w_ce_av;
Tw_prim   = Tw_3d(:,:,iday)-Tw_av;

wt_te_prim = w_te_prim.*Tw_prim;
wt_ne_prim = w_ne_prim.*Tw_prim;
wt_le_prim = w_le_prim.*Tw_prim;
wt_ce_prim = w_ce_prim.*Tw_prim;
% -----------------------------

% --- compute cumulative sum (csum) --- 
wt_te_prim_csum = wt_te_prim_csum + wt_te_prim;
wt_ne_prim_csum = wt_ne_prim_csum + wt_ne_prim;
wt_le_prim_csum = wt_le_prim_csum + wt_le_prim;
wt_ce_prim_csum = wt_ce_prim_csum + wt_ce_prim;
% ---------------

% --- compute number of loops ---
Ndays = Ndays + 1;
% -------------------------------

% --- clear vars to save memory --- 
clear w_te_prim w_ne_prim w_le_prim w_ce_prim Tw_prim 
clear wt_te_prim wt_ne_prim wt_le_prim wt_ce_prim 
% ---------------------------------
end

% --- clear vars to save memory --- 
  clear w_te_3d w_ne_3d w_le_3d w_ce_3d Tw_3d ntime 
% ---------------------------------

  end
end

% --- compute mean vertical heat flux ---
Q_te = rho_w.*Cp.*wt_te_prim_csum ./ Ndays;
Q_ne = rho_w.*Cp.*wt_ne_prim_csum ./ Ndays;
Q_le = rho_w.*Cp.*wt_le_prim_csum ./ Ndays;
Q_ce = rho_w.*Cp.*wt_ce_prim_csum ./ Ndays;
% ---------------------------------------
% ==================
  
  
%% === output data ===
save(outfileQ,'header','lon_1d','lat_1d','Ndays', ...
  'z_wvel_ce','z_Tw','Q_te','Q_ne','Q_le','Q_ce') 
% ====================
